// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0--rc2
// source: proto/api/v1/pinger.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GodoClient is the client API for Godo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GodoClient interface {
	// Ping ...
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type godoClient struct {
	cc grpc.ClientConnInterface
}

func NewGodoClient(cc grpc.ClientConnInterface) GodoClient {
	return &godoClient{cc}
}

func (c *godoClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/internal.Godo/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GodoServer is the server API for Godo service.
// All implementations must embed UnimplementedGodoServer
// for forward compatibility
type GodoServer interface {
	// Ping ...
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedGodoServer()
}

// UnimplementedGodoServer must be embedded to have forward compatible implementations.
type UnimplementedGodoServer struct {
}

func (UnimplementedGodoServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGodoServer) mustEmbedUnimplementedGodoServer() {}

// UnsafeGodoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GodoServer will
// result in compilation errors.
type UnsafeGodoServer interface {
	mustEmbedUnimplementedGodoServer()
}

func RegisterGodoServer(s grpc.ServiceRegistrar, srv GodoServer) {
	s.RegisterService(&Godo_ServiceDesc, srv)
}

func _Godo_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GodoServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Godo/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GodoServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Godo_ServiceDesc is the grpc.ServiceDesc for Godo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Godo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internal.Godo",
	HandlerType: (*GodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Godo_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api/v1/pinger.proto",
}
